<%@ Page Title="" Language="C#" MasterPageFile="~/EN/MasterPageEN.master" AutoEventWireup="true" CodeFile="services.aspx.cs" Inherits="EN_services" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="banner">
            	<img src="img/services/img_bannerservices.jpg">
            </div>
		  <!-- InstanceEndEditable -->
            
          <div id="bannershadow"><img src="img/home/img_bannershadow.png"></div>

          <div id="center">
        	<div id="tital"><img src="img/services/img_titallogo.jpg" alt="">　Practice Areas</div>
            <div id="content_about">
            <ul>
            	<li><img src="img/home/dot.png"> <span class="font_bunder">Introduction</span>
					<p>　　Kaohsiung Office has extensive experiences in relevant areas of legal expertise.  Through community outreach and timely response to clients' inquiries, we have established excellent reputation in client services in South Taiwan. Upholding professionalism and excellence and through long-standing relationship with accountants, we provide deliberated and efficient analyses and assessments on disputes and legal risks faced by our clients.  As a result, Kaohsiung Office has earned the trust and praise from long-term corporate and individual clients by providing integrated services for legal and financial solutions.</p><br>
              	</li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Arbitration and Litigation Practice(Civil, Criminal, and Administrative Litigation)</span>
                	<p>　　Arbitration is a method of dispute resolution based on the autonomy of private law which highly respects the autonomy of the interested parties and has many advantages such as efficiency, effectiveness, expertise of judgment, and observation of confidentiality.  Once the arbitrator has made a determination, the arbitration becomes final and binding, which provides the same effectiveness as the final judgment rendered by the court.  Arbitration enables the interested parties to reduce and avoid the burden of lawsuits and is usually chosen by the interested parties as the dispute resolution method for construction, commercial, and other contract performance disputes.  Kaohsiung Office has extensive experiences in arbitration.</p><br>
               	  	<p>　　Moreover, civil, criminal, and administrative litigation are the core competencies of the practice of law.  Differing from litigation of the past, modern litigation tends toward specialization and sophistication.  Understanding that one person cannot handle the diversity of issues encountered by modern litigation, Kaohsiung Office staffs cases by teaming our lawyers in accordance with their qualifications, experiences, and specialization.  Fully utilizing each attorney's professional background and through discussions and teamwork collaboration, Kaohsiung Office succeeds to serve the best interests and protect the rights of its clients.</p><br>
                    <p>　　Litigation is just one method of dispute resolution among various options for resolving civil disputes.  Mediation, negotiation, and arbitration are increasingly becoming mainstream procedures for resolving such disputes.  We have accumulated extensive experiences in mediation, arbitration and other non-litigation procedures.  Our litigation expertise encompasses a wide range of disputes, including torts, contracts, labor disputes, family law, real estate transactions, financial instruments, negotiable instruments, shareholder disputes, government procurement, and public infrastructure projects.</p><br>
                    <p>　　Kaohsiung Office also represents clients in criminal cases related to specialized fields, for example, allegations or offenses involving financial regulations, construction regulations, environmental regulations, and government procurement.  Kaohsiung Office represents all such cases with vigor and has demonstrated considerable success in defending our clients' rights and interests. </p><br>
                    <p>　　The key to administrative litigation is the study of the Interpretation of Grand Justice Council, court precedents, and relevant interpretative letters of explanation from competent authorities.  Due to the influence of our former Managing Partner, Mr. C.Y. Tsai, who had professional background in public law and was well versed in this field, Kaohsiung Office staffs attorneys with specialization in public law on our team.  As such, we are experts in research and analysis of relevant precedents, regulations, and letters of explanation from the central administering authorities and are well positioned to provide full and comprehensive legal assessments to our clients and reach favorable results. </p><br>
              	</li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Corporate Legal Consultation</span>
                	<p>　　Kaohsiung Office has been retained as external counsel by numerous companies in various industries, varying from technology to traditional manufacturing.  Our consultation services include relevant laws and decrees governing publicly traded companies and over-the-counter markets; contract drafting and negotiation; advising on the applicability of commercial rules, laws, and/or regulations; review of company rules and policies; and analysis of dispute resolution strategy.  Kaohsiung Office has accumulated extensive practical experiences in providing efficient assessment and consultation services to corporations, thus enabling us, like a family doctor for companies, to assist companies in addressing potential legal risks, thereby effectively reducing the cost of and impact on their operations.</p><br>
                </li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Legal Due Diligence Review</span>
                	<p>　　The government has implemented policies that encourage economies of scale and relax channels of capital injection.  As a result, in recent years companies either have expanded or adjusted operational scale or amount of capital through merger and acquisition, divesture, and initial public offering.  However, in order to assess possible financial and legal risks accurately when encountering such significant adjustments of management strategy, companies must first understand the practical value of the target company and its potential legal risks via strict legal due diligence review, which, pursuant to the rules and procedures regulated by the administering authority, must be based on the legal opinion letters issued by attorneys as the basis of compliance evaluation.  Our professional team also has accumulated specialized experiences in this field to provide legal due diligence review and issue legal opinion letters efficiently, timely, and in cooperation with accountants and financial advisors. </p><br>
                </li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Contract Drafting, Review, and Counseling</span>
                	<p>　　As to legal issues which a company may encounter in its daily operations, Kaohsiung Office is also well positioned to provide the company with relevant advice and legal services efficiently and accurately, including drafting, reviewing, and negotiating various business contracts.  Through the process of drafting, reviewing, and negotiating contracts, we assist the company in identifying and managing associated risks in advance, so that possible disputes can be prevented and lengthy dispute resolution processes avoided. </p><br>
                    <p>　　As specialized lawyers, Kaohsiung Office's major concern is providing analysis of relevant legal risks to our clients before the clients make business decisions.  Our philosophy behind the provision of contracts consultation services is the prevention of disputes.  We thus provide contracts drafting, reviewing, and negotiating services under this guiding principle. </p><br>
                </li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Public Construction and BOT/PPP</span>
                	<p>　　It has been more than ten years since the promulgation of the Act for Promotion of Private Participation in Infrastructure Projects (February 9, 2000) ("Act"), which is the legal authority for the private capitalization of public infrastructure projects in our country.  A total of thirteen infrastructure categories are enumerated in the Act, including transportation facilities, major commercial facilities, agricultural facilities, culture and educational facilities, major facilities for tour sites, sanitation and medical facilities and sport facilities.  All projects meeting the categories included in the Act are eligible for private participation and capitalization in accordance with the requirements of each individual category.  As a result  of the variety of infrastructure categories, multiple ways of private participation, and the relevant administrative regulations involved in different infrastructure categories, legal planning and legal consultation have become indispensable parts of projects under the Act.  Moreover, because in recent years project planning by private entities has surfaced gradually in addition to government projects, how the private investors or the coordinating agency properly completes the infrastructure projects pursuant to legal requirements through the advice of specialized counsel has taken on even more significant importance.</p><br>
                    <p>　　Kaohsiung Office has extensive experiences with transportation facilities, major commercial facilities, agricultural facilities, culture and educational facilities, major facilities for tour sites, sanitation and medical facilities, sport facilities, and other projects.  Kaohsiung Office has served as legal counsel both for the public sector and the private sector on numerous occasions.  Our expertise include the following:  advise on feasibility assessment of projects planned by the government or proposed by the private entity; assistance in advance planning; drafting of tender document and investment contract, negotiation of contract, and execution of contract; professional construction management; and mediation of subsequent disputes, including convening mediation committee, arbitration, and litigation.  In that capacity, we strive to improve the quality of public services by reasonably  looking after the interests of both the public sector and the private entities.</p><br>
                </li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Government Procurement Disputes</span>
                	<p>　　Kaohsiung Office has long served on well known construction projects in southern Taiwan as legal counsel for supervision and professional construction management ("PCM"). We have accumulated extensive experiences in theoretical and practical aspects of domestic infrastructure projects, including  mass transit system, roads and bridges, airports, public recreational facilities, sewage lines, and office buildings. Recent specific construction project representation includes Kaohsiung Maritime Cultural Popular Music Center, Kaohsiung Public Library General Library, and Kaohsiung Exhibition and Convention Center.  In addition to drafting of government procurement contracts, related consultation of bidding preparation, the process of tender, review of tender, review of international design competition contracts, and interpretation and alteration of performing contract period, Kaohsiung office also has in depth practical procurement experiences on dispute mediation of construction claims, arbitration, litigation, criminal defense of public official corruption charges.  We are able to provide professional, efficient, and high quality legal services.</p><br>
                    <p>Advise on government procurement cases, including:<br>
                    	<ul>
                        	<li>A.　The process of tender, review of tender, decision of tender:</li>
                            <li>　　&#8226; Analysis of relevant acts for government procurement.</li>
                            <li>　　&#8226; Review of tender document.</li>
                            <li>　　&#8226; Settlement of disputes in the procedure for bid planning and tender opening.</li>
                            <li>　　&#8226; Legal consultation.</li>
                        	
                        	<li>B.　Professional construction management:</li>
                            <li>　　&#8226; Review of contract and management of performance progress.</li>
                            <li>　　&#8226; Consultation of contract disputes.</li>
                            <li>　　&#8226; Settlement of relevant payment disputes.</li>
                            
                            <li>C.　Settlement of disputes:</li>
                            <li>　　&#8226; Civil, criminal and administrative litigation of government procurement.</li>
                            <li>　　&#8226; Opposition, petition, and mediation of government procurement.</li>
                            <li>　　&#8226; Arbitration of government procurement.</li>
                        </ul>
					</p><br>
                </li>
                <li><img src="img/home/dot.png"> <span class="font_bunder">Initial Public Offering ("IPO"), Including overseas companies listed in Taiwan.</span>
                	<p>　　A company may, with the operational scale reaching certain degree and due to capital and expansion requirements, apply for an approval for public issuance of its shares.  Kaohsiung Office assists clients in properly modifying the Articles of Incorporation to comply with relevant regulations governing securities exchange in order to complete the public issuance process successfully.  Furthermore, through the pre-listing due diligence process,  we assist the company to discover existing legal risks in the management of the company and advise on methods of improvement to enhance the value of the company.</p><br>
                    <p>　　In recent years, relevant regulations governing securities in Taiwan offer numerous incentives for "Homecoming of Taiwanese Companies," attracting vibrant overseas-based Taiwanese companies to return to Taiwan for listing purposes.  Kaohsiung Office also has experiences in assisting these companies.  The scope of our services include assisting overseas companies in reincorporating before being listed in Taiwan; advising on compliance with relevant rules and regulations; requesting foreign lawyers to provide legal due diligence review for overseas companies and then issue legal opinion letter; reviewing the offering circular and other listing documents, and serving as legal consultant for securities underwriters of overseas companies listing in Taiwan.  In addition, we review the legal opinion and review result made by overseas company's lawyer, and assist securities underwriters in reviewing the Offering Circular and other legal documents of overseas companies. </p><br>
                </li>
			</ul>
			</div>
        <div class="top"><a href="#top"></a></div>
        </div>
</asp:Content>

